Repository ipfs/package-managers, pull requests merged in 2019-05, with the labels that each got.

#51 SIG-ness
  README.md
Labels: in progress

#53 Move documents into /docs folder
  README.md
  docs/abstractions.md
  docs/blockers.md
  docs/categories.md
  docs/concepts.md
  docs/decentralization.md
  docs/glossary.md
  docs/linking.md
  docs/papers.md
  docs/problems.md
  docs/readme.md
  docs/tree.md
Labels: Status: In progress

#62 Update readme.md
  docs/readme.md
Labels: Type: Documentation
